id = "c3"
name = "C3"
description = "C3 support."
version = "0.1.0"
schema_version = 1
authors = ["ElonGaties"]
repository = "https://github.com/ElonGaties/zed-c3"

[language_servers.c3]
name = "C3"
language = "c3"

[grammars.c3]
repository = "https://github.com/c3lang/tree-sitter-c3"
commit = "2ca9901ae3180b64586dcf9189d56d0c22734d77"
